export const Events = [
  {
    eventTitle: "Lagos Comedy Night",
    eventCategory: "Comedy",
    venue: "Eko Hotel & Suites, Lagos",
    numberAttending: "1000",
    startDate: "16-06-2026",
    startTime: "07:00PM",
    regular_ticketPrice: "5000",
    vip_ticketPrice: "10000",
    vvip_ticketPrice: "15000",
  },
  {
    eventTitle: "Afrobeats Live Concert",
    eventCategory: "Music",
    venue: "Tafawa Balewa Square, Lagos",
    numberAttending: "3500",
    startDate: "25-07-2026",
    startTime: "08:00PM",
    regular_ticketPrice: "12000",
    vip_ticketPrice: "24000",
    vvip_ticketPrice: "36000",
  },
  {
    eventTitle: "Tech Innovators Summit",
    eventCategory: "Technology",
    venue: "Landmark Centre, Lagos",
    numberAttending: "1200",
    startDate: "05-08-2026",
    startTime: "09:00AM",
    regular_ticketPrice: "15000",
    vip_ticketPrice: "30000",
    vvip_ticketPrice: "45000",
  },
  {
    eventTitle: "Startup Pitch Fest",
    eventCategory: "Business",
    venue: "Civic Centre, Lagos",
    numberAttending: "800",
    startDate: "12-08-2026",
    startTime: "10:00AM",
    regular_ticketPrice: "10000",
    vip_ticketPrice: "20000",
    vvip_ticketPrice: "30000",
  },
  {
    eventTitle: "Port Harcourt Food Carnival",
    eventCategory: "Food",
    venue: "Pleasure Park, Port Harcourt",
    numberAttending: "2500",
    startDate: "20-08-2026",
    startTime: "01:00PM",
    regular_ticketPrice: "3000",
    vip_ticketPrice: "6000",
    vvip_ticketPrice: "9000",
  },
  {
    eventTitle: "Fashion Week Nigeria",
    eventCategory: "Fashion",
    venue: "Federal Palace Hotel, Lagos",
    numberAttending: "1800",
    startDate: "02-09-2026",
    startTime: "05:00PM",
    regular_ticketPrice: "8000",
    vip_ticketPrice: "16000",
    vvip_ticketPrice: "24000",
  },
  {
    eventTitle: "Basketball Championship",
    eventCategory: "Sports",
    venue: "Teslim Balogun Stadium, Lagos",
    numberAttending: "5000",
    startDate: "10-09-2026",
    startTime: "04:00PM",
    regular_ticketPrice: "4000",
    vip_ticketPrice: "8000",
    vvip_ticketPrice: "12000",
  },
  {
    eventTitle: "Art & Culture Expo",
    eventCategory: "Art",
    venue: "Nike Art Gallery, Lagos",
    numberAttending: "600",
    startDate: "15-09-2026",
    startTime: "11:00AM",
    regular_ticketPrice: "2500",
    vip_ticketPrice: "5000",
    vvip_ticketPrice: "7500",
  },
  {
    eventTitle: "Digital Marketing Masterclass",
    eventCategory: "Education",
    venue: "Radisson Blu, Ikeja",
    numberAttending: "450",
    startDate: "18-09-2026",
    startTime: "09:00AM",
    regular_ticketPrice: "20000",
    vip_ticketPrice: "40000",
    vvip_ticketPrice: "60000",
  },
  {
    eventTitle: "Youth Leadership Conference",
    eventCategory: "Conference",
    venue: "International Conference Centre, Abuja",
    numberAttending: "1500",
    startDate: "25-09-2026",
    startTime: "10:00AM",
    regular_ticketPrice: "7000",
    vip_ticketPrice: "14000",
    vvip_ticketPrice: "21000",
  },
  {
    eventTitle: "Gospel Praise Festival",
    eventCategory: "Religious",
    venue: "Freedom Park, Lagos",
    numberAttending: "4000",
    startDate: "01-10-2026",
    startTime: "06:00PM",
    regular_ticketPrice: "2000",
    vip_ticketPrice: "4000",
    vvip_ticketPrice: "6000",
  },
  {
    eventTitle: "Movie Premiere Night",
    eventCategory: "Entertainment",
    venue: "Filmhouse Cinema, Lekki",
    numberAttending: "700",
    startDate: "08-10-2026",
    startTime: "07:30PM",
    regular_ticketPrice: "6000",
    vip_ticketPrice: "12000",
    vvip_ticketPrice: "18000",
  },
  {
    eventTitle: "Crypto & Blockchain Meetup",
    eventCategory: "Technology",
    venue: "Workstation, Victoria Island",
    numberAttending: "500",
    startDate: "12-10-2026",
    startTime: "03:00PM",
    regular_ticketPrice: "5000",
    vip_ticketPrice: "10000",
    vvip_ticketPrice: "15000",
  },
  {
    eventTitle: "Women in Tech Forum",
    eventCategory: "Technology",
    venue: "The Zone, Gbagada",
    numberAttending: "850",
    startDate: "18-10-2026",
    startTime: "09:30AM",
    regular_ticketPrice: "7500",
    vip_ticketPrice: "15000",
    vvip_ticketPrice: "22500",
  },
  {
    eventTitle: "Beach Party Experience",
    eventCategory: "Party",
    venue: "Elegushi Beach, Lagos",
    numberAttending: "2200",
    startDate: "24-10-2026",
    startTime: "08:00PM",
    regular_ticketPrice: "10000",
    vip_ticketPrice: "20000",
    vvip_ticketPrice: "30000",
  },
  {
    eventTitle: "Photography Workshop",
    eventCategory: "Education",
    venue: "Terra Kulture, Lagos",
    numberAttending: "300",
    startDate: "30-10-2026",
    startTime: "10:00AM",
    regular_ticketPrice: "4500",
    vip_ticketPrice: "9000",
    vvip_ticketPrice: "13500",
  },
  {
    eventTitle: "Health & Wellness Fair",
    eventCategory: "Health",
    venue: "University of Lagos Sports Centre",
    numberAttending: "900",
    startDate: "05-11-2026",
    startTime: "08:00AM",
    regular_ticketPrice: "1500",
    vip_ticketPrice: "3000",
    vvip_ticketPrice: "4500",
  },
  {
    eventTitle: "E-Sports Championship",
    eventCategory: "Gaming",
    venue: "YabaTech Event Hall, Lagos",
    numberAttending: "1400",
    startDate: "12-11-2026",
    startTime: "02:00PM",
    regular_ticketPrice: "3500",
    vip_ticketPrice: "7000",
    vvip_ticketPrice: "10500",
  },
  {
    eventTitle: "Black Friday Shopping Expo",
    eventCategory: "Shopping",
    venue: "Muri Okunola Park, Lagos",
    numberAttending: "3000",
    startDate: "27-11-2026",
    startTime: "09:00AM",
    regular_ticketPrice: "1000",
    vip_ticketPrice: "2000",
    vvip_ticketPrice: "3000",
  },
  {
    eventTitle: "New Year Countdown Concert",
    eventCategory: "Music",
    venue: "Onikan Stadium, Lagos",
    numberAttending: "10000",
    startDate: "31-12-2026",
    startTime: "09:00PM",
    regular_ticketPrice: "15000",
    vip_ticketPrice: "30000",
    vvip_ticketPrice: "45000",
  },
];