import type { TicketTier } from "@/types/tickets";

export const TicketTiers: TicketTier[] = [
  {
    id: "1",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "TechFest West Africa",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Best Experience",
  },
  {
    id: "2",
    ticketTier: "VVIP",
    tierSubtitle: "Special Reservation",
    event: "Lagos Comedy Fiesta",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 3000,
    status: "Sold Out",
    description: "Special Reservation",
  },
  {
    id: "3",
    ticketTier: "Free",
    tierSubtitle: "Limited benefits",
    event: "Lagos Fashion Week",
    price: 0,
    isFree: true,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Limited benefits",
  },
  {
    id: "4",
    ticketTier: "Regular",
    tierSubtitle: "Regular sitting area",
    event: "Wellness Weekend",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Regular sitting area",
  },
  {
    id: "5",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "Startup Summit",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Best Experience",
  },
  {
    id: "6",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "Afro Art Exhibition",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Best Experience",
  },
  {
    id: "7",
    ticketTier: "Free",
    tierSubtitle: "Limited benefits",
    event: "APCON Watch Party",
    price: 0,
    isFree: true,
    total: 5000,
    sold: 4800,
    status: "Sold Out",
    description: "Limited benefits",
  },
  {
    id: "8",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "Art Exhibition",
    price: 27000,
    isFree: false,
    total: 2800,
    sold: 1800,
    status: "Low Stock",
    description: "Best Experience",
  },
  {
    id: "9",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "AI Tech Workshop",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Best Experience",
  },
  {
    id: "10",
    ticketTier: "VIP",
    tierSubtitle: "Best Experience",
    event: "Fitness Journey",
    price: 27000,
    isFree: false,
    total: 3000,
    sold: 1800,
    status: "Confirmed",
    description: "Best Experience",
  },
];
